name: flutter_al_law
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: 3.26.0
  get_storage: ^1.4.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  crypto: ^2.1.5
  flutter_svg: ^0.19.3
  flutter_bloc: ^6.1.3
  flutter_spinkit: ^4.1.2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  im_stepper: ^0.1.2+10
  date_time_picker: ^1.1.1
  dropdown_search: ^0.4.8
  auto_size_text: ^2.1.0
  flutter_speed_dial: ^2.1.1
  uuid: ^2.2.2
  flutter_local_notifications: ^4.0.1+2
  url_launcher: ^5.7.10
  rxdart: ^0.25.0
  flutter_overlay_loader: ^0.0.2
  auto_animated: ^2.1.0
  share_plus: ^1.2.0
  flutter_rating_bar: ^3.2.0+1

  http: ^0.12.2
  csv: ^4.1.0

dev_dependencies:
  analyzer: 0.41.2
  intl: 0.16.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pngs/
